### ISSUE TITLE
Typings support requested

### ISSUE THREAD

**Issue by erikvullings** [vagusX/koa-proxies#43]
Thanks for creating and sharing this great library: it makes it very easy to proxy requests to other sites. 

As I'm using TypeScript, I was wondering if you would consider adding a typings file to the project too, making it easier to import your library using `import proxies from 'koa-proxies';`? Currently, I need to add the following code snippet to my project in file `koa-proxies.d.ts`:

```ts
declare module "koa-proxies" {
  export interface IKoaProxies {
    target: string;
    changeOrigin?: boolean;
    logs?: boolean;
    agent?: any;
    rewrite?: (path: string) => string;
  }

  export default function proxy(path: string, options: IKoaProxies): Promise;
}
```
In order to support it directly out-of-the-box, all you need to do is add an `index.d.ts`, e.g. 

```ts
export interface IKoaProxies {
  target: string;
  changeOrigin?: boolean;
  logs?: boolean;
  agent?: any;
  rewrite?: (path: string) => string;
}

export default function proxy(path: string, options: IKoaProxies): Promise;
```
and add a reference to it in the package.json, i.e. this 

```json
  "main": "index.js",
  "scripts": { 
```

becomes

```json
  "main": "index.js",
  "typings": "index.d.ts",
  "scripts": {
```

**Comment by vagusX** [comment]
good idea
