### ISSUE TITLE
should not modify options

### ISSUE THREAD

**Issue by lianzhao** [vagusX/koa-proxies#8]
May I know why you deleted three properties from the `opts` at [Lin52](https://github.com/vagusX/koa-proxies/blob/master/index.js#L52)?

**Comment by vagusX** [comment]
These three opts including `'logs', 'rewrite', 'events'` are not the options for `node-http-proxy` and only used by `koa-proxies` itself. 
And what's more, I am considering to split options into `koa-proxies` own options and `node-http-proxy` options. Aiming at more clear options.

**Comment by lianzhao** [comment]
I think the `opts` object is provided by user and does not expected to be modified
